---

- name: Find mongo hostname
  set_fact:
    hname: mongo{{ groups.mongo.index(inventory_hostname) + 1 }}
  when: "'mongo' in group_names"

- name: Find nuxeo hostname
  set_fact:
    hname: nuxeo{{ groups.nuxeo.index(inventory_hostname) + 1 }}
  when: "'nuxeo' in group_names"

- name: Find elastic hostname
  set_fact:
    hname: elastic{{ groups.es.index(inventory_hostname) + 1 }}
  when: "'es' in group_names"

- name: Find management hostname
  set_fact:
    hname: management{{ groups.management.index(inventory_hostname) + 1 }}
  when: "'management' in group_names"

- name: Set hostname
  shell: hostname {{ hname }}

- name: Update /etc/hostname
  shell: echo -n {{ hname }} > /etc/hostname

- name: Backup hosts
  shell: cp /etc/hosts /etc/hosts.bak

- name: Set /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
