- name: Base packages
  apt: name="locales" state=present

- name: Base packages
  apt: name="unzip" state=present

- name: Base packages
  apt: name="curl" state=present

- name: Base packages
  apt: name="emacs" state=present

- name: Base packages
  apt: name="python-pygments" state=present

- name: Check for /etc/default/locale
  stat: path=/etc/default/locale
  register: locale_path
- name: Generate en_US.UTF-8 locale
  shell: locale-gen en_US.UTF-8
  when: locale_path.stat.exists == false
- name: Reconfigure locales package
  shell: dpkg-reconfigure locales
  when: locale_path.stat.exists == false
- name: Generate /etc/default/locale
  shell: update-locale LANG=en_US.UTF-8
  when: locale_path.stat.exists == false
- name: Install public SSH key
  authorized_key: user={{ sshuser }}
                  key="{{ lookup('file', item) }}"
                  state=present
  with_fileglob:
    - id_rsa*
