---
- name: Check for snapshot
  set_fact:
    nuxeo_is_snapshot: "{{'-SNAPSHOT' in nuxeo_version or '-SNAPSHOT' in nuxeo_distribution|default('')}}"
- name: Nuxeo user
  user: name={{nuxeo_user}} home={{nuxeo_base}} createhome=yes shell=/bin/bash state=present uid={{nuxeo_user_uid}}
  when: stage is not defined or stage == 'init'
- name: Nuxeo init.d script
  template: src=nuxeo.init dest=/etc/init.d/{{nuxeo_service_name}} mode=0755
  when: stage is not defined or stage == 'init'
- name: Enable init.d script
  service: name={{nuxeo_service_name}} enabled=yes
  when: stage is not defined or stage == 'init'
- name: Validate distribution variables
  fail: msg="You must define nuxeo_version (even for local/custom distributions)"
  when: nuxeo_version is not defined and (stage is not defined or stage == 'init')
- name: Install dependencies
  include: dependencies.yml
  when: stage is not defined or stage == 'init'
- name: Install mffmpeg
  include: ffmpeg.yml
  when: (stage is not defined or stage == 'init') and installffmpeg
- name: Get distribution
  include: get_distribution.yml
  when: stage is not defined or stage == 'init'

- name: Stop nuxeo
  include: stop.yml
  when: stage is not defined or stage == 'stop'

- name: Update distribution
  include: update_distribution.yml
  #when: distribution_changed|bool and (stage is not defined or stage == 'setup')
  when: stage is not defined or stage == 'setup'

- name: Install hotfixes
  include: install_hotfixes.yml
  when: (stage is not defined or stage == 'setup') and installhotfixes

- name: Set nuxeo log level
  template: src=log4j.xml dest={{nuxeo_base}}/server/lib/ mode=0644
  when: stage is not defined or stage == 'setup'

- name: Start nuxeo
  include: start.yml
  when: stage is not defined or stage == 'start'

# Add screenrc
- name: Add screen conf
  copy: src=screenrc dest=/home/ubuntu/.screenrc owner=ubuntu force=no
